<?php
// ตรวจสอบว่าฟอร์มถูกส่งมาแบบ POST
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // รับข้อมูลจากฟอร์มด้วยการเช็คว่ามีคีย์ใน $_POST หรือไม่
    $member_number = isset($_POST['member_number']) ? $_POST['member_number'] : "ไม่ได้กรอกข้อมูล";
    $date = isset($_POST['date']) ? $_POST['date'] : "ไม่ได้กรอกข้อมูล";
    $first_name = isset($_POST['first_name']) ? $_POST['first_name'] : "ไม่ได้กรอกข้อมูล";
    $surname = isset($_POST['surname']) ? $_POST['surname'] : "ไม่ได้กรอกข้อมูล";
    $dob = isset($_POST['dob']) ? $_POST['dob'] : "ไม่ได้กรอกข้อมูล";
    $age = isset($_POST['age']) ? $_POST['age'] : "ไม่ได้กรอกข้อมูล";
    $sex = isset($_POST['sex']) ? $_POST['sex'] : "ไม่ได้กรอกข้อมูล";
    $nationality = isset($_POST['nationality']) ? $_POST['nationality'] : "ไม่ได้กรอกข้อมูล";
    $agency = isset($_POST['agency']) ? $_POST['agency'] : "ไม่ได้กรอกข้อมูล";
    $businesstype = isset($_POST['businesstype']) ? $_POST['businesstype'] : "ไม่ได้กรอกข้อมูล";
    $addresscom = isset($_POST['addresscom']) ? $_POST['addresscom'] : "ไม่ได้กรอกข้อมูล";
    $swine = isset($_POST['swine']) ? $_POST['swine'] : "ไม่ได้กรอกข้อมูล";
    $alley = isset($_POST['alley']) ? $_POST['alley'] : "ไม่ได้กรอกข้อมูล";
    $road = isset($_POST['road']) ? $_POST['road'] : "ไม่ได้กรอกข้อมูล";
    $district = isset($_POST['district']) ? $_POST['district'] : "ไม่ได้กรอกข้อมูล";
    $canton = isset($_POST['canton']) ? $_POST['canton'] : "ไม่ได้กรอกข้อมูล";
    $province = isset($_POST['province']) ? $_POST['province'] : "ไม่ได้กรอกข้อมูล";
    $zipcode = isset($_POST['zipcode']) ? $_POST['zipcode'] : "ไม่ได้กรอกข้อมูล";
    $mobilephone = isset($_POST['mobilephone']) ? $_POST['mobilephone'] : "ไม่ได้กรอกข้อมูล";
    $phone = isset($_POST['phone']) ? $_POST['phone'] : "ไม่ได้กรอกข้อมูล";
    $fax = isset($_POST['fax']) ? $_POST['fax'] : "ไม่ได้กรอกข้อมูล";
    $email = isset($_POST['email']) ? $_POST['email'] : "ไม่ได้กรอกข้อมูล";
    $currentaddress = isset($_POST['currentaddress']) ? $_POST['currentaddress'] : "ไม่ได้กรอกข้อมูล";
    $swine = isset($_POST['swine']) ? $_POST['swine'] : "ไม่ได้กรอกข้อมูล";
    $alley = isset($_POST['alley']) ? $_POST['alley'] : "ไม่ได้กรอกข้อมูล";
    $road = isset($_POST['road']) ? $_POST['road'] : "ไม่ได้กรอกข้อมูล";
    $district = isset($_POST['district']) ? $_POST['district'] : "ไม่ได้กรอกข้อมูล";
    $canton = isset($_POST['canton']) ? $_POST['canton'] : "ไม่ได้กรอกข้อมูล";
    $province = isset($_POST['province']) ? $_POST['province'] : "ไม่ได้กรอกข้อมูล";
    $zipcode = isset($_POST['zipcode']) ? $_POST['zipcode'] : "ไม่ได้กรอกข้อมูล";
    $mobilephone = isset($_POST['mobilephone']) ? $_POST['mobilephone'] : "ไม่ได้กรอกข้อมูล";
    $phone = isset($_POST['phone']) ? $_POST['phone'] : "ไม่ได้กรอกข้อมูล";
    $idline = isset($_POST['idline']) ? $_POST['idline'] : "ไม่ได้กรอกข้อมูล";
    $email = isset($_POST['email']) ? $_POST['email'] : "ไม่ได้กรอกข้อมูล";
    $company = isset($_POST['company']) ? $_POST['company'] : "ไม่ได้กรอกข้อมูล";
    $home = isset($_POST['home']) ? $_POST['home'] : "ไม่ได้กรอกข้อมูล";
    $vc = isset($_POST['vc']) ? $_POST['vc'] : "ไม่ได้กรอกข้อมูล";
    $hvc = isset($_POST['hvc']) ? $_POST['hvc'] : "ไม่ได้กรอกข้อมูล";
    $bachelor = isset($_POST['bachelor']) ? $_POST['bachelor'] : "ไม่ได้กรอกข้อมูล";
    $faculty = isset($_POST['faculty']) ? $_POST['faculty'] : "ไม่ได้กรอกข้อมูล";
    $branch = isset($_POST['branch']) ? $_POST['branch'] : "ไม่ได้กรอกข้อมูล";
    $university = isset($_POST['university']) ? $_POST['university'] : "ไม่ได้กรอกข้อมูล";
    $faculty = isset($_POST['faculty']) ? $_POST['faculty'] : "ไม่ได้กรอกข้อมูล";
    $branch = isset($_POST['branch']) ? $_POST['branch'] : "ไม่ได้กรอกข้อมูล";
    $university = isset($_POST['university']) ? $_POST['university'] : "ไม่ได้กรอกข้อมูล";
    $building = isset($_POST['building']) ? $_POST['building'] : "ไม่ได้กรอกข้อมูล";
    $licensenumber = isset($_POST['licensenumber']) ? $_POST['licensenumber'] : "ไม่ได้กรอกข้อมูล";
    $pow = isset($_POST['pow']) ? $_POST['pow'] : "ไม่ได้กรอกข้อมูล";
    $licensenumber = isset($_POST['licensenumber']) ? $_POST['licensenumber'] : "ไม่ได้กรอกข้อมูล";
    $private = isset($_POST['private']) ? $_POST['private'] : "ไม่ได้กรอกข้อมูล";
    $licensenumber = isset($_POST['licensenumber']) ? $_POST['licensenumber'] : "ไม่ได้กรอกข้อมูล";
    $career = isset($_POST['career']) ? $_POST['career'] : "ไม่ได้กรอกข้อมูล";
    $person = isset($_POST['person']) ? $_POST['person'] : "ไม่ได้กรอกข้อมูล";
    $associateperson = isset($_POST['associateperson']) ? $_POST['associateperson'] : "ไม่ได้กรอกข้อมูล";
    $oneyear = isset($_POST['oneyear']) ? $_POST['oneyear'] : "ไม่ได้กรอกข้อมูล";
    $fiveyear = isset($_POST['fiveyear']) ? $_POST['fiveyear'] : "ไม่ได้กรอกข้อมูล";
    $oneyear = isset($_POST['oneyear']) ? $_POST['oneyear'] : "ไม่ได้กรอกข้อมูล";
    $fiveyear = isset($_POST['fiveyear']) ? $_POST['fiveyear'] : "ไม่ได้กรอกข้อมูล";
    $corporation = isset($_POST['corporation']) ? $_POST['corporation'] : "ไม่ได้กรอกข้อมูล";
    $associatejuristicperson = isset($_POST['associatejuristicperson']) ? $_POST['associatejuristicperson'] : "ไม่ได้กรอกข้อมูล";
    $oneyear = isset($_POST['oneyear']) ? $_POST['oneyear'] : "ไม่ได้กรอกข้อมูล";
    $fiveyear = isset($_POST['fiveyear']) ? $_POST['fiveyear'] : "ไม่ได้กรอกข้อมูล";
    $oneyear = isset($_POST['oneyear']) ? $_POST['oneyear'] : "ไม่ได้กรอกข้อมูล";
    $fiveyear = isset($_POST['fiveyear']) ? $_POST['fiveyear'] : "ไม่ได้กรอกข้อมูล";
    $cash = isset($_POST['cash']) ? $_POST['cash'] : "ไม่ได้กรอกข้อมูล";
    $transfermoney = isset($_POST['transfermoney']) ? $_POST['transfermoney'] : "ไม่ได้กรอกข้อมูล";
    $agree = isset($_POST['agree']) ? $_POST['agree'] : "ไม่ได้กรอกข้อมูล";
    $disagree = isset($_POST['disagree']) ? $_POST['disagree'] : "ไม่ได้กรอกข้อมูล";
    // แสดงข้อมูลที่ผู้ใช้กรอก
    echo "เลขที่สมาชิก: $member_number\n";
    echo "วัน/เดือน/ปี: $date\n";
    echo "ชื่อ: $first_name\n";
    echo "นามสกุล: $surname\n";
    echo "วันเกิด: $dob\n";
    echo "อายุ: $age\n";
    echo "เพศ: $sex\n";
    echo "สัญชาติ: $nationality\n";
    echo "หน่วยงาน/บริษัท (Agency/Company) : $agency\n";
    echo "ประเภทธุรกิจ (Business Type) : $businesstype\n";
    echo "ที่อยู่บริษัท :  $addresscom\n";
    echo "หมู่ :  $swine\n";
    echo "ตรอก/ซอย :  $alley\n";
    echo "ถนน :  $road\n";
    echo "ตำบล/แขวง :  $district\n";
    echo "อำเภอ/เขต :  $canton\n";
    echo "จังหวัด : $province\n";
    echo "รหัสไปรษณีย์ :  $zipcode\n";
    echo "โทรศัพท์/มือถือ :  $mobilephone\n";
    echo "โทรศัพท์ :  $phone\n";
    echo "โทรสาร :  $fax\n";
    echo "Email :  $email\n";
    echo "ที่อยู่ปัจจุบัน :  $currentaddress\n";
    echo "หมู่ :  $swine\n";
    echo "ตรอก/ซอย :  $alley\n";
    echo "ถนน :  $road\n";
    echo "ตำบล/แขวง :  $district\n";
    echo "อำเภอ/เขต :  $canton\n";
    echo "จังหวัด : $province\n";
    echo "รหัสไปรษณีย์ :  $zipcode\n";
    echo "โทรศัพท์/มือถือ :  $mobilephone\n";
    echo "โทรศัพท์ :  $phone\n";
    echo "โทรสาร :  $fax\n";
    echo "ID Line : $idline\n";
    echo "Email :  $email\n";
    echo "ที่อยู่บริษัท (Company) : $company\n";
    echo "ที่อยู่ปัจจุบัน (Home) : $home\n";
    echo "ปวช. (Vocational Certificate) : $vc\n";
    echo "ปวส. (High Vocational Certificate) : $hvc\n";
    echo "ปริญญาตรี (Bachelor) คณะ : $faculty\n";
    echo "สาขาวิชา : $branch\n";
    echo "สถาบัน/มหาวิทยาลัย : $university\n";
    echo "ปริญญาโท หรือ สูงกว่า(Master of Higher) คณะ :  : $faculty\n";
    echo "สาขาวิชา : $branch\n";
    echo "สถาบัน/มหาวิทยาลัย : $licensenumber\n";
} else {
    echo "ไม่มีข้อมูลที่ถูกส่งมา\n";
}
?>
